[project]
authors = ["horned_axe <horned_axe@proton.me>"]
channels = ["nvidia", "conda-forge", "pytorch"]
description = "Add a short description here"
name = "CIRNet_TIP2022"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.8"
cuda = {version = "*", channel = "nvidia"}
pytorch = {version = "1.10.1", channel = "pytorch"}
torchvision = {version = "0.11.2", channel = "pytorch"}
pytorch-cuda = {version = "*", channel = "pytorch"}
mkl = "2024.0"
opencv = "*"
pillow = "*"
tensorboardX = "*"
