[project]
authors = ["horned_axe <horned_axe@proton.me>"]
channels = ["nvidia/label/cuda-12.4.0","nvidia", "conda-forge", "pytorch"]
description = "Add a short description here"
name = "CIRNet_TIP2022"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12"
cuda = {version = "*", channel = "nvidia/label/cuda-12.4.0"}
pytorch = {version = ">=2.0", channel = "pytorch"}
torchvision = {version = "*", channel = "pytorch"}
opencv = "*"
pillow = "*"
tensorboardX = "*"
